"""
API / UI serialization: last-line defense so junk placeholders never leave the backend.

Use ``serialize_car_for_api`` for JSON responses and embedded listing payloads.
Templates can use Jinja filters ``format_display_value`` / ``engine_display`` registered in ``main``.

This module was split into cohesive submodules (``_common``, ``engine``, ``bmw``,
``location_tco``, ``condition``, ``serialize``) behind this facade. Every name that
was importable from ``backend.utils.car_serialize`` before the split is re-exported
here, so ``from backend.utils.car_serialize import X`` is unchanged.
"""
from __future__ import annotations

from ._common import (
    DISPLAY_DASH,
    SENSITIVE_CAR_ROW_KEYS,
    _dealer_spec_wins,
    _EPA_MODE_AGGREGATE_RE,
    _format_mpg_city_highway,
    _MANUFACTURER_SPEC_RE,
    _strip_epa_aggregate_label,
    _transmission_line_has_gear_count,
    _transmission_phrase_prefer_detail,
    format_display_value,
    logger,
    redact_sensitive_car_row,
)
from .bmw import (
    _BMW_MODEL_TAIL,
    _BMW_MOTOR_TRIM_PREFIX_RE,
    _BMW_SRC_CPO_MARKERS,
    _bmw_resolve_condition_for_display,
    _bmw_series_trim_from_motor_model,
    _bmw_title_suffix_trim,
    _bmw_trace_vin_enabled,
    _strip_bmw_trim_series_prefix,
    apply_bmw_model_trim_display,
)
from .condition import (
    fill_derived_condition_for_display,
    infer_condition_for_storage,
    listings_inventory_is_new,
    listings_inventory_is_pre_owned,
    normalize_condition_for_storage,
)
from .engine import (
    _cylinder_layout_token,
    _DISP_ONLY_ENGINE_RE,
    _effective_cylinder_count,
    _effective_fuel_type_for_display,
    _ENGINE_FAMILY_CODE_RE,
    _ENGINE_FUEL_SUFFIX_RE,
    _ENGINE_INLINE_TECH_RE,
    _ENGINE_JUNK_PARENS_RE,
    _ENGINE_MILD_HYBRID_PARENS_RE,
    _extract_liters_from_engine_text,
    _format_engine_l_numeric_liters,
    _fuel_word,
    _infer_layout_from_vehicle,
    _is_displacement_only_engine_text,
    _known_trim_engine_display,
    _layout_token_from_engine_text,
    _normalize_engine_description,
    _sticker_engine_display_from_packages,
    build_engine_display,
    car_matches_engine_displacement_l_range,
    infer_engine_l_for_db,
    parse_engine_displacement_liters,
)
from .location_tco import (
    _COMMA_STATE_ZIP_RE,
    _engine_spec_text_for_fuel_requirement,
    _extract_state_from_location_text,
    _normalize_tco_make_key,
    _state_from_dealership_registry,
    _STATE_ZIP_IN_TEXT_RE,
    _TCO_DEFAULT_STATE,
    _TCO_LUXURY_PREMIUM_MAKES,
    _TCO_PREMIUM_ENGINE_KEYWORDS,
    _TRAILING_COMMA_STATE_RE,
    _valid_us_state_code,
    resolve_car_fuel_requirement,
    resolve_car_state_code,
)
from .serialize import (
    _format_mileage_mi,
    _latest_price_drop_for_grid,
    _LISTINGS_GRID_GALLERY_MAX,
    _package_names_from_raw,
    _parse_gallery_url_list,
    _price_history_for_vdp,
    _price_history_json_for_vdp,
    _PRICE_DROP_RECENT_DAYS,
    _public_gallery_photo_count,
    _listings_grid_gallery,
    build_detail_display_snapshot,
    serialize_car_for_api,
    serialize_car_for_listings_grid,
)

__all__ = [
    # public names
    "DISPLAY_DASH",
    "SENSITIVE_CAR_ROW_KEYS",
    "apply_bmw_model_trim_display",
    "build_detail_display_snapshot",
    "build_engine_display",
    "car_matches_engine_displacement_l_range",
    "fill_derived_condition_for_display",
    "format_display_value",
    "infer_condition_for_storage",
    "infer_engine_l_for_db",
    "listings_inventory_is_new",
    "listings_inventory_is_pre_owned",
    "logger",
    "normalize_condition_for_storage",
    "parse_engine_displacement_liters",
    "redact_sensitive_car_row",
    "resolve_car_fuel_requirement",
    "resolve_car_state_code",
    "serialize_car_for_api",
    "serialize_car_for_listings_grid",
    # private names still imported by other modules / historically importable
    "_BMW_MODEL_TAIL",
    "_BMW_MOTOR_TRIM_PREFIX_RE",
    "_BMW_SRC_CPO_MARKERS",
    "_COMMA_STATE_ZIP_RE",
    "_DISP_ONLY_ENGINE_RE",
    "_ENGINE_FAMILY_CODE_RE",
    "_ENGINE_FUEL_SUFFIX_RE",
    "_ENGINE_INLINE_TECH_RE",
    "_ENGINE_JUNK_PARENS_RE",
    "_ENGINE_MILD_HYBRID_PARENS_RE",
    "_EPA_MODE_AGGREGATE_RE",
    "_LISTINGS_GRID_GALLERY_MAX",
    "_MANUFACTURER_SPEC_RE",
    "_PRICE_DROP_RECENT_DAYS",
    "_STATE_ZIP_IN_TEXT_RE",
    "_TCO_DEFAULT_STATE",
    "_TCO_LUXURY_PREMIUM_MAKES",
    "_TCO_PREMIUM_ENGINE_KEYWORDS",
    "_TRAILING_COMMA_STATE_RE",
    "_bmw_resolve_condition_for_display",
    "_bmw_series_trim_from_motor_model",
    "_bmw_title_suffix_trim",
    "_bmw_trace_vin_enabled",
    "_cylinder_layout_token",
    "_dealer_spec_wins",
    "_effective_cylinder_count",
    "_effective_fuel_type_for_display",
    "_engine_spec_text_for_fuel_requirement",
    "_extract_liters_from_engine_text",
    "_extract_state_from_location_text",
    "_format_engine_l_numeric_liters",
    "_format_mileage_mi",
    "_format_mpg_city_highway",
    "_fuel_word",
    "_infer_layout_from_vehicle",
    "_is_displacement_only_engine_text",
    "_known_trim_engine_display",
    "_latest_price_drop_for_grid",
    "_layout_token_from_engine_text",
    "_listings_grid_gallery",
    "_normalize_engine_description",
    "_normalize_tco_make_key",
    "_package_names_from_raw",
    "_parse_gallery_url_list",
    "_price_history_for_vdp",
    "_price_history_json_for_vdp",
    "_public_gallery_photo_count",
    "_state_from_dealership_registry",
    "_sticker_engine_display_from_packages",
    "_strip_bmw_trim_series_prefix",
    "_strip_epa_aggregate_label",
    "_transmission_line_has_gear_count",
    "_transmission_phrase_prefer_detail",
    "_valid_us_state_code",
]
