#!/usr/bin/env python3
"""
Capture the live inventory schema as ``migrations/V001__baseline.sql``.

The chain has to start from what production actually has, not from what
``init_postgres_inventory()`` would create -- those have drifted apart through
years of ad-hoc ALTERs, and only the server knows by how much. So the baseline
is a pg_dump of the running database: schema only, never data.

Run this ONCE, at the head of the chain. After V001 exists, schema changes are
new numbered files; re-dumping the baseline would rewrite an applied migration
and the runner will (correctly) refuse to run.

Existing databases must be told they already have this schema rather than being
made to execute it:

  python -m backend.scripts.dump_baseline_schema --write
  python -m backend.scripts.migrate --baseline 1 --apply

Usage:
  python -m backend.scripts.dump_baseline_schema             # dry run: print the pg_dump it would run
  python -m backend.scripts.dump_baseline_schema --write
  python -m backend.scripts.dump_baseline_schema --write --force   # overwrite an existing baseline
"""
from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from backend.utils.project_env import load_project_dotenv

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("dump_baseline_schema")

DEFAULT_OUT = _REPO_ROOT / "migrations" / "V001__baseline.sql"

# --no-owner / --no-privileges: a rebuilt dev or CI database has no "railway"
# role, and GRANTs to a role that does not exist abort the restore.
# --schema-only is the whole contract here: this file is DDL, never rows.
PG_DUMP_ARGS = [
    "--schema-only",
    "--no-owner",
    "--no-privileges",
    "--no-comments",
]


def _redact(dsn: str) -> str:
    """Hide the password before a DSN reaches the log."""
    if "@" not in dsn:
        return dsn
    creds, _, host = dsn.partition("@")
    scheme, _, userpass = creds.partition("://")
    user = userpass.split(":", 1)[0]
    return f"{scheme}://{user}:***@{host}"


def build_command(dsn: str) -> list[str]:
    return ["pg_dump", *PG_DUMP_ARGS, dsn]


def _strip_psql_only(sql: str) -> tuple[str, list[str]]:
    """
    Drop lines only ``psql`` can run, so the baseline survives ``migrate.py``.

    pg_dump >= 17.6 wraps plain-format output in ``\\restrict`` / ``\\unrestrict``
    meta-commands, and a 17.x client emits ``SET transaction_timeout`` even when
    dumping an older server. The migration chain is executed through psycopg,
    not psql, so the first of those is a syntax error at ``\\`` and the second is
    an unrecognized-parameter error against PG < 17. There is no pg_dump flag to
    suppress either.
    """
    kept: list[str] = []
    dropped: list[str] = []
    for line in sql.splitlines(keepends=True):
        bare = line.strip()
        if bare.startswith(("\\restrict", "\\unrestrict")) or bare.startswith(
            "SET transaction_timeout"
        ):
            dropped.append(bare)
            continue
        kept.append(line)
    return "".join(kept), dropped


def _header(dsn: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        "-- V001__baseline.sql\n"
        "--\n"
        "-- Generated by backend/scripts/dump_baseline_schema.py from the live\n"
        f"-- inventory database at {stamp} (pg_dump --schema-only).\n"
        "--\n"
        "-- This is the starting point of the migration chain: a database created\n"
        "-- from this file plus every later V<NNN> file matches production. Do not\n"
        "-- edit it -- change the schema with a new numbered migration instead.\n"
        "--\n\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="run pg_dump and write the file (default: dry run)")
    parser.add_argument("--dry-run", action="store_true",
                        help="explicit no-op default; print the command and exit")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing baseline (see the warning above)")
    parser.add_argument("--out", default=str(DEFAULT_OUT),
                        help=f"output path (default: {DEFAULT_OUT})")
    args = parser.parse_args(argv)

    load_project_dotenv()
    write = args.write and not args.dry_run

    from backend.db.inventory_pg import inventory_postgres_dsn

    dsn = inventory_postgres_dsn()
    if not dsn:
        log.error("INVENTORY_DATABASE_URL (or DATABASE_URL) must point at postgresql://")
        return 2

    out = Path(args.out)
    if out.exists() and not args.force:
        log.error("%s already exists. The baseline is applied history -- regenerating "
                  "it changes a migration other databases have already run. Use "
                  "--force only if nothing has applied it yet.", out)
        return 2
    if not shutil.which("pg_dump"):
        log.error("pg_dump not found on PATH (brew install libpq / postgresql-client)")
        return 2

    cmd = build_command(dsn)
    log.info("pg_dump %s %s", " ".join(PG_DUMP_ARGS), _redact(dsn))
    if not write:
        log.info("dry run: would write %s -- re-run with --write", out)
        return 0

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        log.error("pg_dump failed (%d): %s", proc.returncode, proc.stderr.strip()[:2000])
        return 1
    if "CREATE TABLE" not in proc.stdout:
        # An empty-looking dump means we pointed at the wrong database; writing it
        # would enshrine an empty schema as the baseline.
        log.error("pg_dump returned no CREATE TABLE statements -- wrong database?")
        return 1

    body, dropped = _strip_psql_only(proc.stdout)
    if dropped:
        log.info("dropped %d psql-only/incompatible line(s): %s",
                 len(dropped), ", ".join(sorted({d.split()[0] for d in dropped})))
    stray = [ln for ln in body.splitlines() if ln.startswith("\\")]
    if stray:
        # Refuse rather than write a baseline that dies on its first line. A
        # future pg_dump can add new meta-commands; this catches them loudly.
        log.error("pg_dump emitted psql meta-commands this script does not know "
                  "how to strip (%s) -- refusing to write an unusable baseline",
                  ", ".join(sorted({s.split()[0] for s in stray})[:5]))
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_header(dsn) + body, encoding="utf-8")
    log.info("wrote %s (%d bytes)", out, out.stat().st_size)
    log.info("existing databases: python -m backend.scripts.migrate --baseline 1 --apply")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
