-- V001__baseline.sql
--
-- Generated by backend/scripts/dump_baseline_schema.py from the live
-- inventory database at 2026-07-29 14:28:13 UTC (pg_dump --schema-only).
--
-- This is the starting point of the migration chain: a database created
-- from this file plus every later V<NNN> file matches production. Do not
-- edit it -- change the schema with a new numbered migration instead.
--

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10 (Homebrew)
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dblink; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS dblink WITH SCHEMA public;


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: refresh_vehicle_search_vector(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.refresh_vehicle_search_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', COALESCE(NEW.make,        '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW.model,       '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW.trim,        '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(NEW.body_style,  '')), 'C') ||
    setweight(to_tsvector('english', COALESCE(NEW.fuel_type,   '')), 'C') ||
    setweight(to_tsvector('english', COALESCE(NEW.engine_desc, '')), 'D') ||
    setweight(to_tsvector('english', COALESCE(NEW.notes,       '')), 'D');
  RETURN NEW;
END;
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_engine_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_engine_specs (
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    engine_description text DEFAULT ''::text NOT NULL,
    cylinders integer,
    fuel_type text DEFAULT ''::text NOT NULL,
    horsepower integer,
    torque_lb_ft integer,
    tow_capacity_lb integer,
    zero_to_60_sec double precision,
    fuel_tank_gal double precision,
    curb_weight_lb integer,
    specs_json jsonb,
    source_host text DEFAULT 'ai-engine-research'::text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ai_model_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_model_specs (
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    horsepower integer,
    torque_lb_ft integer,
    torque_nm integer,
    curb_weight_lb integer,
    curb_weight_kg integer,
    zero_to_60_sec double precision,
    fuel_tank_gal double precision,
    tow_capacity_lb integer,
    specs_json jsonb,
    source_host text DEFAULT 'ai-research'::text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: cars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars (
    id bigint NOT NULL,
    vin text NOT NULL,
    title text,
    year integer,
    make text,
    model text,
    "trim" text,
    price double precision,
    mileage integer,
    fuel_type text,
    cylinders integer,
    transmission text,
    drivetrain text,
    exterior_color text,
    interior_color text,
    image_url text,
    dealer_name text,
    dealer_url text,
    scraped_at text,
    dealer_id text,
    stock_number text,
    gallery text,
    carfax_url text,
    history_highlights text,
    msrp double precision,
    dealership_registry_id integer,
    source_url text,
    body_style text,
    engine_description text,
    transmission_type text,
    condition text,
    description text,
    data_quality_score double precision,
    is_cpo integer,
    model_full_raw text,
    mpg_city integer,
    mpg_highway integer,
    engine_l text,
    recovery_status text,
    recovery_attempted_at text,
    recovery_source text,
    recovery_notes text,
    missing_field_count integer,
    recoverability_score double precision,
    spec_source_json text,
    packages text,
    listing_active integer DEFAULT 1,
    listing_removed_at text,
    interior_color_buckets text,
    first_seen_at text,
    last_price_change_at text,
    internal_notes text,
    marked_for_review integer,
    price_provenance_json text,
    window_sticker_url text,
    forced_induction text,
    zip_code text,
    spin_frames text,
    interior_pano text,
    epa_master_id bigint,
    epa_match_confidence double precision,
    epa_match_method text
);


--
-- Name: cars_backup_capacity_20260718; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_capacity_20260718 (
    id bigint,
    vin text,
    title text,
    year integer,
    make text,
    model text,
    "trim" text,
    price double precision,
    mileage integer,
    fuel_type text,
    cylinders integer,
    transmission text,
    drivetrain text,
    exterior_color text,
    interior_color text,
    image_url text,
    dealer_name text,
    dealer_url text,
    scraped_at text,
    dealer_id text,
    stock_number text,
    gallery text,
    carfax_url text,
    history_highlights text,
    msrp double precision,
    dealership_registry_id integer,
    source_url text,
    body_style text,
    engine_description text,
    transmission_type text,
    condition text,
    description text,
    data_quality_score double precision,
    is_cpo integer,
    model_full_raw text,
    mpg_city integer,
    mpg_highway integer,
    engine_l text,
    recovery_status text,
    recovery_attempted_at text,
    recovery_source text,
    recovery_notes text,
    missing_field_count integer,
    recoverability_score double precision,
    spec_source_json text,
    packages text,
    listing_active integer,
    listing_removed_at text,
    interior_color_buckets text,
    first_seen_at text,
    last_price_change_at text,
    internal_notes text,
    marked_for_review integer,
    price_provenance_json text,
    window_sticker_url text,
    forced_induction text,
    zip_code text,
    spin_frames text,
    interior_pano text
);


--
-- Name: cars_backup_mcpeek_prescan_20260712; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_mcpeek_prescan_20260712 (
    id bigint,
    vin text,
    stock_number text,
    mileage integer,
    exterior_color text,
    interior_color text,
    drivetrain text,
    transmission text,
    engine_description text
);


--
-- Name: cars_backup_mileage_contam_20260712; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_mileage_contam_20260712 (
    id bigint,
    vin text,
    stock_number text,
    mileage integer
);


--
-- Name: cars_backup_modelname_20260712; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_modelname_20260712 (
    id bigint,
    model text
);


--
-- Name: cars_backup_stock_contam_20260711_171841; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_stock_contam_20260711_171841 (
    id bigint,
    vin text,
    stock_number text,
    drivetrain text,
    transmission text,
    exterior_color text,
    interior_color text
);


--
-- Name: cars_backup_stock_contam_20260711_171901; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_stock_contam_20260711_171901 (
    id bigint,
    vin text,
    stock_number text,
    drivetrain text,
    transmission text,
    exterior_color text,
    interior_color text
);


--
-- Name: cars_backup_vinrepair_20260713; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cars_backup_vinrepair_20260713 (
    id bigint,
    make text,
    model text,
    vin text
);


--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cars_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.cars_id_seq OWNED BY public.cars.id;


--
-- Name: catalog_exterior_colors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_exterior_colors (
    id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    color_name character varying(100) NOT NULL,
    color_code character varying(20),
    finish_type character varying(20),
    hex_code character(7),
    extra_cost integer DEFAULT 0 NOT NULL
);


--
-- Name: catalog_interior_colors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_interior_colors (
    id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    color_name character varying(100) NOT NULL,
    color_code character varying(20),
    material character varying(30),
    hex_code character(7),
    extra_cost integer DEFAULT 0 NOT NULL
);


--
-- Name: catalog_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_options (
    id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    option_code character varying(20),
    option_name character varying(150) NOT NULL,
    option_msrp integer,
    category character varying(50),
    description text
);


--
-- Name: catalog_package_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_package_features (
    id bigint NOT NULL,
    package_id bigint NOT NULL,
    feature_name character varying(150) NOT NULL,
    feature_category character varying(50),
    sort_order smallint DEFAULT 0 NOT NULL
);


--
-- Name: catalog_packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_packages (
    id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    package_code character varying(20),
    package_name character varying(150) NOT NULL,
    package_msrp integer,
    is_required boolean DEFAULT false NOT NULL,
    sort_order smallint DEFAULT 0 NOT NULL,
    notes text
);


--
-- Name: catalog_trims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalog_trims (
    id bigint NOT NULL,
    year smallint NOT NULL,
    make character varying(50) NOT NULL,
    model character varying(100) NOT NULL,
    "trim" character varying(100) NOT NULL,
    body_style character varying(50),
    trim_level smallint DEFAULT 1,
    engine_l numeric(3,1),
    engine_desc character varying(100),
    cylinders smallint,
    horsepower smallint,
    torque_lb_ft smallint,
    fuel_type character varying(30),
    forced_induction character varying(25) DEFAULT 'None'::character varying,
    transmission character varying(30),
    trans_speeds smallint,
    drivetrain character varying(10),
    mpg_city smallint,
    mpg_highway smallint,
    mpg_combined smallint,
    range_miles smallint,
    base_msrp integer,
    source character varying(20) DEFAULT 'epa'::character varying NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    search_vector tsvector,
    embedding public.vector(1536),
    CONSTRAINT vehicles_year_check CHECK (((year >= 2000) AND (year <= 2030)))
);


--
-- Name: dealer_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_catalog (
    dealer_id text NOT NULL,
    registry_id bigint,
    provider text,
    inventory_mode text,
    inventory_endpoint text,
    site_config_json text DEFAULT '{}'::text NOT NULL,
    last_vin_fingerprint text,
    scan_interval_hours integer DEFAULT 24 NOT NULL,
    next_scan_at text,
    onboarded_at text,
    last_scan_at text,
    updated_at text NOT NULL
);


--
-- Name: dealer_geopoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_geopoints (
    dealer_url text NOT NULL,
    dealer_name text,
    lat double precision,
    lon double precision,
    zip_code text,
    city text,
    state text,
    geocode_source text,
    geocoded_at text DEFAULT (CURRENT_TIMESTAMP)::text
);


--
-- Name: dealer_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_jobs (
    id bigint NOT NULL,
    dealer_id text NOT NULL,
    job_type text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    payload_json text DEFAULT '{}'::text NOT NULL,
    worker_id text,
    created_at text NOT NULL,
    started_at text,
    finished_at text,
    error text,
    result_json text DEFAULT '{}'::text NOT NULL
);


--
-- Name: dealer_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dealer_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dealer_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dealer_jobs_id_seq OWNED BY public.dealer_jobs.id;


--
-- Name: dealer_recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_recipes (
    dealer_id text NOT NULL,
    recipes_json text NOT NULL,
    recipe_count integer DEFAULT 0 NOT NULL,
    provider_hint text,
    max_saved_at double precision DEFAULT 0 NOT NULL,
    last_ok_at double precision DEFAULT 0 NOT NULL,
    stale_count integer DEFAULT 0 NOT NULL,
    updated_at text,
    scan_hints text
);


--
-- Name: dealer_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_reviews (
    id bigint NOT NULL,
    dealer_id text NOT NULL,
    user_id integer NOT NULL,
    display_name text,
    is_anonymous integer DEFAULT 0 NOT NULL,
    rating integer NOT NULL,
    body text NOT NULL,
    addon_fee_reported integer DEFAULT 0 NOT NULL,
    addon_fee_amount double precision,
    addon_fee_desc text,
    status text DEFAULT 'published'::text NOT NULL,
    report_count integer DEFAULT 0 NOT NULL,
    ip_hash text,
    created_at text,
    updated_at text
);


--
-- Name: dealer_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dealer_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dealer_reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dealer_reviews_id_seq OWNED BY public.dealer_reviews.id;


--
-- Name: dealer_scan_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_scan_profile (
    dealer_id text NOT NULL,
    last_winning_strategy text,
    platform_hints_json text DEFAULT '[]'::text NOT NULL,
    updated_at text NOT NULL
);


--
-- Name: dealer_specials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_specials (
    id bigint NOT NULL,
    dealer_id text NOT NULL,
    title text,
    type text,
    vehicle_year integer,
    vehicle_make text,
    vehicle_model text,
    vehicle_trim text,
    payment double precision,
    term_months integer,
    due_at_signing double precision,
    mileage_per_year integer,
    msrp double precision,
    expires text,
    fine_print text,
    source_url text,
    raw_html_snippet text,
    offer_hash text,
    scraped_at text NOT NULL
);


--
-- Name: dealer_specials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dealer_specials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dealer_specials_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dealer_specials_id_seq OWNED BY public.dealer_specials.id;


--
-- Name: dealer_vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealer_vehicles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    vin text NOT NULL,
    title text,
    year integer,
    make text,
    model text,
    "trim" text,
    price double precision,
    mileage integer,
    transmission text,
    drivetrain text,
    fuel_type text,
    exterior_color text,
    interior_color text,
    cylinders integer,
    body_style text,
    engine_description text,
    stock_number text,
    notes text,
    gallery_json text DEFAULT '[]'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);


--
-- Name: dealer_vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dealer_vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dealer_vehicles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dealer_vehicles_id_seq OWNED BY public.dealer_vehicles.id;


--
-- Name: dealerships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dealerships (
    id bigint NOT NULL,
    name text NOT NULL,
    website_url text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    latitude double precision,
    longitude double precision,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
    duplicate_of_id bigint,
    duplicate_score double precision,
    is_active integer DEFAULT 1 NOT NULL,
    street_address text,
    zip_code text,
    dealer_website_url text,
    source_dmv integer DEFAULT 0 NOT NULL,
    source_osm integer DEFAULT 0 NOT NULL,
    source_web integer DEFAULT 0 NOT NULL,
    osm_id text,
    sticker_provider text DEFAULT 'unknown'::text NOT NULL,
    sticker_ipacket_fail_count integer DEFAULT 0 NOT NULL,
    sticker_provider_updated_at text,
    google_place_id text,
    google_rating double precision,
    google_review_count integer,
    google_rating_fetched_at text,
    oem_brand text,
    business_status text,
    google_primary_type text,
    phone text,
    platform text,
    strategy text
);


--
-- Name: dealerships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dealerships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dealerships_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dealerships_id_seq OWNED BY public.dealerships.id;


--
-- Name: dictionary_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dictionary_options (
    id bigint NOT NULL,
    year integer,
    make text,
    model text,
    "trim" text,
    engine_options text,
    engine_display text,
    forced_induction text,
    transmission text,
    drivetrain text,
    fuel_type text,
    body_style text,
    cylinders integer,
    displacement double precision,
    mpg_city double precision,
    mpg_highway double precision,
    mpg_combined double precision,
    exterior_colors text,
    packages text,
    package_details text,
    options text,
    option_details text
);


--
-- Name: dictionary_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dictionary_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dictionary_options_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dictionary_options_id_seq OWNED BY public.dictionary_options.id;


--
-- Name: epa_extended_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_extended_specs (
    epa_master_id bigint NOT NULL,
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    "trim" text,
    horsepower integer,
    torque_lb_ft integer,
    torque_nm integer,
    curb_weight_lb integer,
    curb_weight_kg integer,
    zero_to_60_sec double precision,
    fuel_tank_gal double precision,
    ev_range_miles integer,
    battery_kwh double precision,
    body_style_detail text,
    specs_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    source_url text,
    source_host text,
    scrape_status text DEFAULT 'pending'::text NOT NULL,
    scraped_at timestamp with time zone,
    last_error text,
    tow_capacity_lb integer
);


--
-- Name: epa_extended_specs_bak_20260711_101806; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_extended_specs_bak_20260711_101806 (
    epa_master_id bigint,
    year integer,
    make text,
    model text,
    "trim" text,
    horsepower integer,
    torque_lb_ft integer,
    torque_nm integer,
    curb_weight_lb integer,
    curb_weight_kg integer,
    zero_to_60_sec double precision,
    fuel_tank_gal double precision,
    ev_range_miles integer,
    battery_kwh double precision,
    body_style_detail text,
    specs_json jsonb,
    source_url text,
    source_host text,
    scrape_status text,
    scraped_at timestamp with time zone,
    last_error text,
    tow_capacity_lb integer
);


--
-- Name: epa_extended_specs_bak_20260712_083724; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_extended_specs_bak_20260712_083724 (
    epa_master_id bigint,
    year integer,
    make text,
    model text,
    "trim" text,
    horsepower integer,
    torque_lb_ft integer,
    torque_nm integer,
    curb_weight_lb integer,
    curb_weight_kg integer,
    zero_to_60_sec double precision,
    fuel_tank_gal double precision,
    ev_range_miles integer,
    battery_kwh double precision,
    body_style_detail text,
    specs_json jsonb,
    source_url text,
    source_host text,
    scrape_status text,
    scraped_at timestamp with time zone,
    last_error text,
    tow_capacity_lb integer
);


--
-- Name: epa_extended_specs_bak_badhp_20260712; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_extended_specs_bak_badhp_20260712 (
    epa_master_id bigint,
    year integer,
    make text,
    model text,
    horsepower integer
);


--
-- Name: epa_extended_specs_bak_badratio_20260712; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_extended_specs_bak_badratio_20260712 (
    epa_master_id bigint,
    year integer,
    make text,
    model text,
    horsepower integer,
    torque_lb_ft integer
);


--
-- Name: epa_master; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_master (
    id bigint NOT NULL,
    epa_vehicle_id integer,
    year integer,
    make text,
    model text,
    cylinders integer,
    displacement double precision,
    trany text,
    drive text,
    fuel_type text,
    city08 double precision,
    highway08 double precision,
    city_e double precision,
    highway_e double precision,
    atv_type text,
    "trim" text,
    body_style text,
    engine_description text,
    engine_display text,
    forced_induction text
);


--
-- Name: epa_master_dump_id_map; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epa_master_dump_id_map (
    dump_id bigint,
    live_id bigint
);


--
-- Name: epa_master_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.epa_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: epa_master_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.epa_master_id_seq OWNED BY public.epa_master.id;


--
-- Name: exterior_colors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.exterior_colors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: exterior_colors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.exterior_colors_id_seq OWNED BY public.catalog_exterior_colors.id;


--
-- Name: incomplete_listings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incomplete_listings (
    car_id bigint NOT NULL,
    vin text NOT NULL,
    missing_fields_json text NOT NULL,
    updated_at text NOT NULL
);


--
-- Name: incomplete_listings_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incomplete_listings_meta (
    k text NOT NULL,
    v text NOT NULL
);


--
-- Name: interior_colors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interior_colors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interior_colors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interior_colors_id_seq OWNED BY public.catalog_interior_colors.id;


--
-- Name: lease_offer_matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lease_offer_matches (
    id bigint NOT NULL,
    dealer_id text NOT NULL,
    offer_hash text NOT NULL,
    offer_id bigint,
    extracted_json text,
    summary text,
    matches_json text,
    match_count integer DEFAULT 0,
    confidence double precision,
    computed_at text NOT NULL
);


--
-- Name: lease_offer_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.lease_offer_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: lease_offer_matches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.lease_offer_matches_id_seq OWNED BY public.lease_offer_matches.id;


--
-- Name: market_price_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_price_stats (
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    "trim" text NOT NULL,
    condition text NOT NULL,
    mileage_band_low integer NOT NULL,
    mileage_band_high integer,
    median_price double precision NOT NULL,
    p25_price double precision NOT NULL,
    p75_price double precision NOT NULL,
    sample_count integer NOT NULL,
    dealer_count integer NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: model_generations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_generations (
    id bigint NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    generation text NOT NULL,
    year_start integer NOT NULL,
    year_end integer,
    notes text,
    status text DEFAULT 'estimated'::text NOT NULL
);


--
-- Name: model_generations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.model_generations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: model_generations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.model_generations_id_seq OWNED BY public.model_generations.id;


--
-- Name: model_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_specs (
    make text NOT NULL,
    model text NOT NULL,
    cylinders integer,
    gears integer,
    transmission text,
    drivetrain text,
    body_style text,
    fuel_type text
);


--
-- Name: nhtsa_vpic_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nhtsa_vpic_cache (
    vin text NOT NULL,
    response_json text NOT NULL,
    fetched_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);


--
-- Name: package_features_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.package_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: package_features_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.package_features_id_seq OWNED BY public.catalog_package_features.id;


--
-- Name: package_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.package_observations (
    id bigint NOT NULL,
    vin text,
    year integer,
    make text,
    model text,
    "trim" text,
    kind text NOT NULL,
    code text,
    raw_name text,
    name_norm text NOT NULL,
    price double precision,
    category text,
    source text NOT NULL,
    seen_at text NOT NULL
);


--
-- Name: package_observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.package_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: package_observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.package_observations_id_seq OWNED BY public.package_observations.id;


--
-- Name: package_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.package_values (
    id bigint NOT NULL,
    year integer,
    make text NOT NULL,
    model text NOT NULL,
    "trim" text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    match_key text NOT NULL,
    name_display text NOT NULL,
    name_norm text NOT NULL,
    code text,
    msrp double precision,
    msrp_source text,
    msrp_authority integer DEFAULT 0 NOT NULL,
    category text,
    observation_count integer DEFAULT 0 NOT NULL,
    sticker_count integer DEFAULT 0 NOT NULL,
    confidence double precision DEFAULT 0 NOT NULL,
    first_seen_at text,
    last_seen_at text
);


--
-- Name: package_values_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.package_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: package_values_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.package_values_id_seq OWNED BY public.package_values.id;


--
-- Name: packages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: packages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.packages_id_seq OWNED BY public.catalog_packages.id;


--
-- Name: saved_cars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_cars (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    car_id bigint NOT NULL,
    saved_at text DEFAULT (CURRENT_TIMESTAMP)::text
);


--
-- Name: saved_cars_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.saved_cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: saved_cars_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.saved_cars_id_seq OWNED BY public.saved_cars.id;


--
-- Name: scan_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scan_runs (
    id bigint NOT NULL,
    dealer_id text NOT NULL,
    dealer_name text,
    finished_at text NOT NULL,
    duration_seconds double precision,
    upserted integer,
    inventory_rows integer,
    deduped_rows integer,
    vdps_visited integer,
    vehicles_vdp_enriched integer,
    error text,
    summary_json text DEFAULT '{}'::text NOT NULL,
    provider text
);


--
-- Name: scan_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scan_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scan_runs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scan_runs_id_seq OWNED BY public.scan_runs.id;


--
-- Name: standalone_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.standalone_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: standalone_options_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.standalone_options_id_seq OWNED BY public.catalog_options.id;


--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vehicles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.vehicles_id_seq OWNED BY public.catalog_trims.id;


--
-- Name: cars id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cars ALTER COLUMN id SET DEFAULT nextval('public.cars_id_seq'::regclass);


--
-- Name: catalog_exterior_colors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_exterior_colors ALTER COLUMN id SET DEFAULT nextval('public.exterior_colors_id_seq'::regclass);


--
-- Name: catalog_interior_colors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_interior_colors ALTER COLUMN id SET DEFAULT nextval('public.interior_colors_id_seq'::regclass);


--
-- Name: catalog_options id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_options ALTER COLUMN id SET DEFAULT nextval('public.standalone_options_id_seq'::regclass);


--
-- Name: catalog_package_features id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_package_features ALTER COLUMN id SET DEFAULT nextval('public.package_features_id_seq'::regclass);


--
-- Name: catalog_packages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_packages ALTER COLUMN id SET DEFAULT nextval('public.packages_id_seq'::regclass);


--
-- Name: catalog_trims id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_trims ALTER COLUMN id SET DEFAULT nextval('public.vehicles_id_seq'::regclass);


--
-- Name: dealer_jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_jobs ALTER COLUMN id SET DEFAULT nextval('public.dealer_jobs_id_seq'::regclass);


--
-- Name: dealer_reviews id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_reviews ALTER COLUMN id SET DEFAULT nextval('public.dealer_reviews_id_seq'::regclass);


--
-- Name: dealer_specials id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_specials ALTER COLUMN id SET DEFAULT nextval('public.dealer_specials_id_seq'::regclass);


--
-- Name: dealer_vehicles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_vehicles ALTER COLUMN id SET DEFAULT nextval('public.dealer_vehicles_id_seq'::regclass);


--
-- Name: dealerships id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealerships ALTER COLUMN id SET DEFAULT nextval('public.dealerships_id_seq'::regclass);


--
-- Name: dictionary_options id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dictionary_options ALTER COLUMN id SET DEFAULT nextval('public.dictionary_options_id_seq'::regclass);


--
-- Name: epa_master id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epa_master ALTER COLUMN id SET DEFAULT nextval('public.epa_master_id_seq'::regclass);


--
-- Name: lease_offer_matches id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lease_offer_matches ALTER COLUMN id SET DEFAULT nextval('public.lease_offer_matches_id_seq'::regclass);


--
-- Name: model_generations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_generations ALTER COLUMN id SET DEFAULT nextval('public.model_generations_id_seq'::regclass);


--
-- Name: package_observations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_observations ALTER COLUMN id SET DEFAULT nextval('public.package_observations_id_seq'::regclass);


--
-- Name: package_values id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_values ALTER COLUMN id SET DEFAULT nextval('public.package_values_id_seq'::regclass);


--
-- Name: saved_cars id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_cars ALTER COLUMN id SET DEFAULT nextval('public.saved_cars_id_seq'::regclass);


--
-- Name: scan_runs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_runs ALTER COLUMN id SET DEFAULT nextval('public.scan_runs_id_seq'::regclass);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: cars cars_vin_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_vin_key UNIQUE (vin);


--
-- Name: dealer_catalog dealer_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_catalog
    ADD CONSTRAINT dealer_catalog_pkey PRIMARY KEY (dealer_id);


--
-- Name: dealer_geopoints dealer_geopoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_geopoints
    ADD CONSTRAINT dealer_geopoints_pkey PRIMARY KEY (dealer_url);


--
-- Name: dealer_jobs dealer_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_jobs
    ADD CONSTRAINT dealer_jobs_pkey PRIMARY KEY (id);


--
-- Name: dealer_recipes dealer_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_recipes
    ADD CONSTRAINT dealer_recipes_pkey PRIMARY KEY (dealer_id);


--
-- Name: dealer_reviews dealer_reviews_dealer_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_reviews
    ADD CONSTRAINT dealer_reviews_dealer_id_user_id_key UNIQUE (dealer_id, user_id);


--
-- Name: dealer_reviews dealer_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_reviews
    ADD CONSTRAINT dealer_reviews_pkey PRIMARY KEY (id);


--
-- Name: dealer_scan_profile dealer_scan_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_scan_profile
    ADD CONSTRAINT dealer_scan_profile_pkey PRIMARY KEY (dealer_id);


--
-- Name: dealer_specials dealer_specials_dealer_id_offer_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_specials
    ADD CONSTRAINT dealer_specials_dealer_id_offer_hash_key UNIQUE (dealer_id, offer_hash);


--
-- Name: dealer_specials dealer_specials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_specials
    ADD CONSTRAINT dealer_specials_pkey PRIMARY KEY (id);


--
-- Name: dealer_vehicles dealer_vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_vehicles
    ADD CONSTRAINT dealer_vehicles_pkey PRIMARY KEY (id);


--
-- Name: dealer_vehicles dealer_vehicles_user_id_vin_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealer_vehicles
    ADD CONSTRAINT dealer_vehicles_user_id_vin_key UNIQUE (user_id, vin);


--
-- Name: dealerships dealerships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealerships
    ADD CONSTRAINT dealerships_pkey PRIMARY KEY (id);


--
-- Name: dictionary_options dictionary_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dictionary_options
    ADD CONSTRAINT dictionary_options_pkey PRIMARY KEY (id);


--
-- Name: epa_extended_specs epa_extended_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epa_extended_specs
    ADD CONSTRAINT epa_extended_specs_pkey PRIMARY KEY (epa_master_id);


--
-- Name: epa_master epa_master_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epa_master
    ADD CONSTRAINT epa_master_pkey PRIMARY KEY (id);


--
-- Name: catalog_exterior_colors exterior_colors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_exterior_colors
    ADD CONSTRAINT exterior_colors_pkey PRIMARY KEY (id);


--
-- Name: catalog_exterior_colors exterior_colors_vehicle_id_color_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_exterior_colors
    ADD CONSTRAINT exterior_colors_vehicle_id_color_name_key UNIQUE (vehicle_id, color_name);


--
-- Name: incomplete_listings_meta incomplete_listings_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incomplete_listings_meta
    ADD CONSTRAINT incomplete_listings_meta_pkey PRIMARY KEY (k);


--
-- Name: incomplete_listings incomplete_listings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incomplete_listings
    ADD CONSTRAINT incomplete_listings_pkey PRIMARY KEY (car_id);


--
-- Name: catalog_interior_colors interior_colors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_interior_colors
    ADD CONSTRAINT interior_colors_pkey PRIMARY KEY (id);


--
-- Name: catalog_interior_colors interior_colors_vehicle_id_color_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_interior_colors
    ADD CONSTRAINT interior_colors_vehicle_id_color_name_key UNIQUE (vehicle_id, color_name);


--
-- Name: lease_offer_matches lease_offer_matches_dealer_id_offer_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lease_offer_matches
    ADD CONSTRAINT lease_offer_matches_dealer_id_offer_hash_key UNIQUE (dealer_id, offer_hash);


--
-- Name: lease_offer_matches lease_offer_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lease_offer_matches
    ADD CONSTRAINT lease_offer_matches_pkey PRIMARY KEY (id);


--
-- Name: market_price_stats market_price_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_price_stats
    ADD CONSTRAINT market_price_stats_pkey PRIMARY KEY (make, model, "trim", year, condition, mileage_band_low);


--
-- Name: model_generations model_generations_make_model_generation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_generations
    ADD CONSTRAINT model_generations_make_model_generation_key UNIQUE (make, model, generation);


--
-- Name: model_generations model_generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_generations
    ADD CONSTRAINT model_generations_pkey PRIMARY KEY (id);


--
-- Name: model_specs model_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_specs
    ADD CONSTRAINT model_specs_pkey PRIMARY KEY (make, model);


--
-- Name: nhtsa_vpic_cache nhtsa_vpic_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhtsa_vpic_cache
    ADD CONSTRAINT nhtsa_vpic_cache_pkey PRIMARY KEY (vin);


--
-- Name: catalog_package_features package_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_package_features
    ADD CONSTRAINT package_features_pkey PRIMARY KEY (id);


--
-- Name: package_observations package_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_observations
    ADD CONSTRAINT package_observations_pkey PRIMARY KEY (id);


--
-- Name: package_observations package_observations_vin_kind_name_norm_source_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_observations
    ADD CONSTRAINT package_observations_vin_kind_name_norm_source_key UNIQUE (vin, kind, name_norm, source);


--
-- Name: package_values package_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_values
    ADD CONSTRAINT package_values_pkey PRIMARY KEY (id);


--
-- Name: package_values package_values_year_make_model_trim_kind_match_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_values
    ADD CONSTRAINT package_values_year_make_model_trim_kind_match_key_key UNIQUE (year, make, model, "trim", kind, match_key);


--
-- Name: catalog_packages packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_packages
    ADD CONSTRAINT packages_pkey PRIMARY KEY (id);


--
-- Name: catalog_packages packages_vehicle_id_package_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_packages
    ADD CONSTRAINT packages_vehicle_id_package_name_key UNIQUE (vehicle_id, package_name);


--
-- Name: saved_cars saved_cars_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_cars
    ADD CONSTRAINT saved_cars_pkey PRIMARY KEY (id);


--
-- Name: saved_cars saved_cars_user_id_car_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_cars
    ADD CONSTRAINT saved_cars_user_id_car_id_key UNIQUE (user_id, car_id);


--
-- Name: scan_runs scan_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_runs
    ADD CONSTRAINT scan_runs_pkey PRIMARY KEY (id);


--
-- Name: catalog_options standalone_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_options
    ADD CONSTRAINT standalone_options_pkey PRIMARY KEY (id);


--
-- Name: catalog_options standalone_options_vehicle_id_option_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_options
    ADD CONSTRAINT standalone_options_vehicle_id_option_name_key UNIQUE (vehicle_id, option_name);


--
-- Name: catalog_trims vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_trims
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: catalog_trims vehicles_year_make_model_trim_engine_drivetrain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_trims
    ADD CONSTRAINT vehicles_year_make_model_trim_engine_drivetrain_key UNIQUE NULLS NOT DISTINCT (year, make, model, "trim", engine_desc, drivetrain);


--
-- Name: idx_cars_active_facet_combo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_active_facet_combo ON public.cars USING btree (make, model, "trim", fuel_type, cylinders, drivetrain, body_style) WHERE (COALESCE(listing_active, 1) = 1);


--
-- Name: idx_cars_active_make; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_active_make ON public.cars USING btree (make) WHERE ((COALESCE(listing_active, 1) = 1) AND (make IS NOT NULL));


--
-- Name: idx_cars_active_packages; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_active_packages ON public.cars USING btree (make, model) WHERE ((COALESCE(listing_active, 1) = 1) AND (packages IS NOT NULL) AND (packages <> ALL (ARRAY['{}'::text, '[]'::text, 'null'::text, ''::text])));


--
-- Name: idx_cars_active_price; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_active_price ON public.cars USING btree (price) WHERE (COALESCE(listing_active, 1) = 1);


--
-- Name: idx_cars_active_registry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_active_registry ON public.cars USING btree (dealership_registry_id) WHERE ((COALESCE(listing_active, 1) = 1) AND (dealership_registry_id IS NOT NULL));


--
-- Name: idx_cars_dealer_listing; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cars_dealer_listing ON public.cars USING btree (dealer_id, listing_active);


--
-- Name: idx_dealer_catalog_next_scan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_catalog_next_scan ON public.dealer_catalog USING btree (next_scan_at);


--
-- Name: idx_dealer_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_jobs_status ON public.dealer_jobs USING btree (status, created_at);


--
-- Name: idx_dealer_reviews_dealer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_reviews_dealer ON public.dealer_reviews USING btree (dealer_id, status);


--
-- Name: idx_dealer_reviews_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_reviews_user ON public.dealer_reviews USING btree (user_id, created_at);


--
-- Name: idx_dealer_specials_dealer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_specials_dealer ON public.dealer_specials USING btree (dealer_id);


--
-- Name: idx_dealer_vehicles_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_vehicles_user ON public.dealer_vehicles USING btree (user_id);


--
-- Name: idx_dealer_vehicles_vin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealer_vehicles_vin ON public.dealer_vehicles USING btree (vin);


--
-- Name: idx_dealerships_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealerships_created ON public.dealerships USING btree (created_at DESC);


--
-- Name: idx_dealerships_google_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealerships_google_place ON public.dealerships USING btree (google_place_id);


--
-- Name: idx_dealerships_zip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dealerships_zip ON public.dealerships USING btree (zip_code);


--
-- Name: idx_dgp_dealer_url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dgp_dealer_url ON public.dealer_geopoints USING btree (dealer_url);


--
-- Name: idx_dict_options_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dict_options_lookup ON public.dictionary_options USING btree (year, make, model);


--
-- Name: idx_dict_options_trim; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dict_options_trim ON public.dictionary_options USING btree (year, make, model, "trim");


--
-- Name: idx_epa_extended_specs_ymm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_epa_extended_specs_ymm ON public.epa_extended_specs USING btree (year, make, model);


--
-- Name: idx_epa_master_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_epa_master_lookup ON public.epa_master USING btree (year, make, model);


--
-- Name: idx_epa_master_trim; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_epa_master_trim ON public.epa_master USING btree (year, make, model, "trim");


--
-- Name: idx_exterior_colors_vehicle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exterior_colors_vehicle ON public.catalog_exterior_colors USING btree (vehicle_id);


--
-- Name: idx_incomplete_listings_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_incomplete_listings_updated ON public.incomplete_listings USING btree (updated_at DESC);


--
-- Name: idx_interior_colors_vehicle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interior_colors_vehicle ON public.catalog_interior_colors USING btree (vehicle_id);


--
-- Name: idx_lease_matches_dealer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lease_matches_dealer ON public.lease_offer_matches USING btree (dealer_id);


--
-- Name: idx_package_features_package; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_package_features_package ON public.catalog_package_features USING btree (package_id);


--
-- Name: idx_package_obs_ymm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_package_obs_ymm ON public.package_observations USING btree (year, make, model, "trim");


--
-- Name: idx_package_values_ymm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_package_values_ymm ON public.package_values USING btree (year, make, model, "trim");


--
-- Name: idx_packages_vehicle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_packages_vehicle ON public.catalog_packages USING btree (vehicle_id);


--
-- Name: idx_scan_runs_dealer_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_runs_dealer_time ON public.scan_runs USING btree (dealer_id, finished_at DESC);


--
-- Name: idx_standalone_options_vehicle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_standalone_options_vehicle ON public.catalog_options USING btree (vehicle_id);


--
-- Name: idx_vehicles_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vehicles_embedding ON public.catalog_trims USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_vehicles_fuel_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vehicles_fuel_type ON public.catalog_trims USING btree (fuel_type);


--
-- Name: idx_vehicles_make; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vehicles_make ON public.catalog_trims USING btree (make);


--
-- Name: idx_vehicles_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vehicles_search ON public.catalog_trims USING gin (search_vector);


--
-- Name: idx_vehicles_year_make_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vehicles_year_make_model ON public.catalog_trims USING btree (year, make, model);


--
-- Name: ux_ai_engine_specs; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_ai_engine_specs ON public.ai_engine_specs USING btree (year, lower(make), lower(model), lower(btrim(engine_description)), COALESCE(cylinders, '-1'::integer), lower(btrim(fuel_type)));


--
-- Name: ux_ai_model_specs_ymm; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_ai_model_specs_ymm ON public.ai_model_specs USING btree (year, lower(make), lower(model));


--
-- Name: catalog_trims trg_vehicles_search_vector; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_vehicles_search_vector BEFORE INSERT OR UPDATE ON public.catalog_trims FOR EACH ROW EXECUTE FUNCTION public.refresh_vehicle_search_vector();


--
-- Name: catalog_trims trg_vehicles_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_vehicles_updated_at BEFORE UPDATE ON public.catalog_trims FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: dealerships dealerships_duplicate_of_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dealerships
    ADD CONSTRAINT dealerships_duplicate_of_id_fkey FOREIGN KEY (duplicate_of_id) REFERENCES public.dealerships(id);


--
-- Name: epa_extended_specs epa_extended_specs_epa_master_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epa_extended_specs
    ADD CONSTRAINT epa_extended_specs_epa_master_id_fkey FOREIGN KEY (epa_master_id) REFERENCES public.epa_master(id) ON DELETE CASCADE;


--
-- Name: catalog_exterior_colors exterior_colors_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_exterior_colors
    ADD CONSTRAINT exterior_colors_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.catalog_trims(id) ON DELETE CASCADE;


--
-- Name: catalog_interior_colors interior_colors_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_interior_colors
    ADD CONSTRAINT interior_colors_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.catalog_trims(id) ON DELETE CASCADE;


--
-- Name: catalog_package_features package_features_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_package_features
    ADD CONSTRAINT package_features_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.catalog_packages(id) ON DELETE CASCADE;


--
-- Name: catalog_packages packages_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_packages
    ADD CONSTRAINT packages_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.catalog_trims(id) ON DELETE CASCADE;


--
-- Name: catalog_options standalone_options_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalog_options
    ADD CONSTRAINT standalone_options_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.catalog_trims(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


