"""Pin the public surface of ``backend.scanner.recipe_synth``.

recipe_synth is a facade over the ``backend.scanner.synth`` package (audit F-6,
2026-10). Scripts, the discovery workflow and tests import public AND private
names from it (``_fetch_impersonated``, ``_pace``, ``_CHALLENGE_MARKERS``,
``_extract_ccid`` ...), so every name the monolith defined or imported for its
callers must stay importable, and the platform registry must keep its order:
:func:`fingerprint_platform` returns the FIRST template whose detect() fires.
"""
from __future__ import annotations

import importlib

FACADE_NAMES = (
    'EndpointRecipe',
    'PAGINATION_ALGOLIA',
    'PAGINATION_CARSCOMMERCE',
    'PAGINATION_COSMOS_PT',
    'PAGINATION_DEALER_COM',
    'PAGINATION_DEP_SRP',
    'PAGINATION_GRAPHQL_OFFSET',
    'PAGINATION_HTML_PAGE',
    'PAGINATION_JAZEL_SRP',
    'PAGINATION_NONE',
    'PAGINATION_PAGE_QUERY',
    'PAGINATION_TYPESENSE',
    'PLATFORM_TEMPLATES',
    'PlatformTemplate',
    'RECIPES_DIR',
    '_APIKEY_RE',
    '_AUTOWALL_LIST_PATH',
    '_AUTOWALL_TOTAL_RE',
    '_BROWSER_UA',
    '_CARSCOMMERCE_HOST',
    '_CARSCOMMERCE_REF_ID',
    '_CCID_RES',
    '_CC_CUSTOM_FACETS',
    '_CC_FACET_CHUNK',
    '_CC_LOCATION_MAP_RE',
    '_CC_PLACE_ONLY_RE',
    '_CC_SINGLE_STORE_MAX',
    '_CC_SINGLE_STORE_MAX_UNSTAMPED',
    '_CHALLENGE_BEACON_MARKERS',
    '_CHALLENGE_MARKERS',
    '_CHAPMAN_API_HOST',
    '_CHAPMAN_ARKONA_RES',
    '_CHAPMAN_CONDITIONS',
    '_COSMOS_ACCOUNT_RES',
    '_COSMOS_ITEMLIST_RE',
    '_COSMOS_PAGE_SIZE',
    '_COSMOS_PATH',
    '_COSMOS_SRP_PATHS',
    '_COSMOS_SRP_PATHS_NEW',
    '_DEALERMASTERS_INDEX_ROUTES',
    '_DEALER_COM_INVENTORY_PATH',
    '_DEALER_COM_REF_ID',
    '_DEALER_COM_REF_SITEID',
    '_DEP_COUNT_RE',
    '_DEP_CT_RE',
    '_DEP_ESCALATE_STATUSES',
    '_DEP_LC_LINK_RE',
    '_DEP_NAV_SRP_RE',
    '_DEP_OPTION_VALUE_RE',
    '_DEP_PAGE_SIZE_CAP',
    '_DEP_PAGE_SIZE_PARAM',
    '_DEP_PAGE_SIZE_SELECT_RE',
    '_DEP_SRP_PATHS',
    '_HTML_CARDS_MIN',
    '_HTML_CARDS_PATHS',
    '_HTML_HARVEST_SRP_PATHS',
    '_JAZEL_SRP_PATH',
    '_MAX_CHALLENGE_SHELL_BYTES',
    '_MIN_FETCH_INTERVAL',
    '_MIN_REAL_HTML_BYTES',
    '_MOTIVE_APIKEY_RE',
    '_MOTIVE_API_KEY',
    '_MOTIVE_APPID_RE',
    '_MOTIVE_APP_ID',
    '_MOTIVE_DEALER_RES',
    '_MOTIVE_HITS_PER_PAGE',
    '_MOTIVE_INDEX_PREFIX',
    '_MOTIVE_INDEX_RE',
    '_MOTIVE_SORT',
    '_NABTHAT_SRP_PATHS',
    '_ONEAUDI_DEALER_RE',
    '_ONEAUDI_GRAPHQL',
    '_ONEAUDI_MARKET_RE',
    '_ONEAUDI_PAGE_SIZE',
    '_ONEAUDI_QUERY',
    '_ONEAUDI_SRP_PATHS',
    '_ONEAUDI_STATIMPORT_RE',
    '_OVERFUEL_SRP_PATH',
    '_RETRYABLE_STATUS',
    '_SITEID_RE',
    '_TEAM_VELOCITY_FEED',
    '_TEAM_VELOCITY_FEEDS',
    '_TEMPLATES_BY_NAME',
    '_TS_COLLECTION_RES',
    '_TS_DEFAULT_QUERY_BY',
    '_TS_HOST_RES',
    '_TS_KEY_RES',
    '_TS_SRP_PATHS',
    '_TYPESENSE_REF_COLLECTION',
    '_TYPESENSE_REF_ID',
    '_VALIDATE_MAX_PAGES',
    '_WP_VEHICLES_PATH',
    '_browser_headers',
    '_carscommerce_store_filter',
    '_cc_facet_census',
    '_cc_location_facets',
    '_cc_rooftop_place',
    '_cc_rooftop_place_of',
    '_cc_rooftop_sig',
    '_cc_verify_store_filter',
    '_chapman_recipe',
    '_cosmos_get_json',
    '_cosmos_pagecfg_from_paths',
    '_dealermasters_static_query_hashes',
    '_dep_condition_bucket',
    '_dep_fetch_html',
    '_dep_fetch_page',
    '_dep_nav_srp_paths',
    '_dep_page_size',
    '_dep_page_vins',
    '_dep_pick_per_condition',
    '_dep_srp_recipe',
    '_dep_store_lc',
    '_detect_autowall',
    '_detect_carscommerce',
    '_detect_chapman',
    '_detect_dealer_com',
    '_detect_dealer_eprocess',
    '_detect_dealer_on_cosmos',
    '_detect_dealermasters',
    '_detect_html_cards',
    '_detect_jazel',
    '_detect_motive',
    '_detect_nabthat',
    '_detect_oneaudi',
    '_detect_overfuel',
    '_detect_sister_tv',
    '_detect_team_velocity',
    '_detect_typesense',
    '_detect_wp_vehicles_index',
    '_extract_carscommerce_key',
    '_extract_ccid',
    '_extract_chapman_arkona',
    '_extract_cosmos_account',
    '_extract_cosmos_pagecfg',
    '_extract_dealer_com_siteid',
    '_extract_motive_dealer_id',
    '_extract_ts_collection',
    '_extract_ts_host',
    '_extract_ts_key',
    '_fetch_impersonated',
    '_fetch_wp_vehicles',
    '_load_reference_recipe',
    '_mutate_for_page',
    '_nabthat_page_vins',
    '_nabthat_recipe',
    '_nrm_facet',
    '_oneaudi_body',
    '_oneaudi_decoded',
    '_oneaudi_inputs',
    '_origin',
    '_pace',
    '_pace_lock',
    '_replay_request',
    '_synth_autowall',
    '_synth_carscommerce',
    '_synth_chapman',
    '_synth_dealer_com',
    '_synth_dealer_eprocess',
    '_synth_dealer_on_cosmos',
    '_synth_dealermasters',
    '_synth_html_cards',
    '_synth_jazel',
    '_synth_motive',
    '_synth_nabthat',
    '_synth_oneaudi',
    '_synth_overfuel',
    '_synth_team_velocity',
    '_synth_typesense',
    '_synth_wp_vehicles_index',
    '_ts_default_body',
    '_ts_ref_key',
    '_tv_feed_recipe',
    '_unique_vins',
    '_url_for_page',
    '_validate_cosmos',
    '_validate_dep',
    '_validate_html_walk',
    '_validate_json_feed',
    '_with_query_param',
    'detect_html_harvest',
    'fetch_dealer_html',
    'fingerprint_platform',
    'harvest_html_vehicles',
    'is_synthesizable',
    'load_recipes',
    'logger',
    'looks_like_challenge',
    'open_url',
    'recipe_is_store_scoped',
    'synthesize_recipe',
    'synthesize_recipes',
    'validate_recipe',
)

# (template name, detect function, synth function) in PLATFORM_TEMPLATES order.
REGISTRY = (
    ('carscommerce', '_detect_carscommerce', '_synth_carscommerce'),
    ('typesense', '_detect_typesense', '_synth_typesense'),
    ('dealer_on_cosmos', '_detect_dealer_on_cosmos', '_synth_dealer_on_cosmos'),
    ('dealer_dot_com', '_detect_dealer_com', '_synth_dealer_com'),
    ('sister_tv', '_detect_sister_tv', None),
    ('team_velocity', '_detect_team_velocity', '_synth_team_velocity'),
    ('dealer_eprocess', '_detect_dealer_eprocess', '_synth_dealer_eprocess'),
    ('motive_ridemotive', '_detect_motive', '_synth_motive'),
    ('overfuel', '_detect_overfuel', '_synth_overfuel'),
    ('nabthat', '_detect_nabthat', '_synth_nabthat'),
    ('chapman', '_detect_chapman', '_synth_chapman'),
    ('jazel', '_detect_jazel', '_synth_jazel'),
    ('dealermasters', '_detect_dealermasters', '_synth_dealermasters'),
    ('wp_vehicles_index', '_detect_wp_vehicles_index', '_synth_wp_vehicles_index'),
    ('autowall', '_detect_autowall', '_synth_autowall'),
    ('oneaudi', '_detect_oneaudi', '_synth_oneaudi'),
    ('html_cards', '_detect_html_cards', '_synth_html_cards'),
)


def test_facade_exports_every_name():
    rs = importlib.import_module("backend.scanner.recipe_synth")
    missing = [n for n in FACADE_NAMES if not hasattr(rs, n)]
    assert missing == []


def test_registry_order_and_wiring_unchanged():
    rs = importlib.import_module("backend.scanner.recipe_synth")
    got = tuple(
        (t.name, t.detect.__name__, t.synth.__name__ if t.synth else None)
        for t in rs.PLATFORM_TEMPLATES
    )
    assert got == REGISTRY
    assert list(rs._TEMPLATES_BY_NAME) == [r[0] for r in REGISTRY]


def test_facade_functions_are_the_registered_ones():
    """The facade's _detect_*/_synth_* are the very objects the registry calls,
    so a test that drives a template through the facade drives the real one."""
    rs = importlib.import_module("backend.scanner.recipe_synth")
    for t in rs.PLATFORM_TEMPLATES:
        assert getattr(rs, t.detect.__name__) is t.detect
        if t.synth is not None:
            assert getattr(rs, t.synth.__name__) is t.synth
