"""Per-make and per-model trim orders: the ladders themselves, as data."""
from __future__ import annotations

import re


MAKE_TRIM_ORDER: dict[str, tuple[str, ...]] = {
    "ford": (
        "Limited",
        "Raptor R",
        "Raptor",
        "Platinum",
        "King Ranch",
        "Lariat",
        "Timberline",
        "Tremor",
        "Titanium",
        "GT",
        "SEL",
        "ST-Line",
        "STX",
        "Sport",
        "FX4",
        "XLT",
        "SE",
        "XL",
        "Active",
        "Base",
    ),
    "chevrolet": (
        "ZR1",
        "Z06",
        "Stingray",
        "High Country",
        "Premier",
        "LTZ",
        "ZR2",
        "SS",
        "Trail Boss",
        "LT Trail Boss",
        "RST",
        "Z71",
        "RS",
        "LT",
        "Custom Trail Boss",
        "Custom",
        "LS",
        "WT",
        "L",
    ),
    "gmc": (
        "Denali Ultimate",
        "AT4X",
        "Denali",
        "AT4",
        "SLT",
        "Elevation",
        "SLE",
        "Pro",
    ),
    "ram": (
        "TRX",
        "Tungsten",
        "Limited",
        "Laramie Longhorn",
        "Laramie",
        "Rebel",
        "Night Edition",
        "Big Horn",
        "Lone Star",
        "Tradesman HFE",
        "Tradesman",
    ),
    "jeep": (
        "Summit Reserve",
        "Summit",
        "Overland",
        "High Altitude",
        "Limited",
        "Rubicon",
        "Trailhawk",
        "Mojave",
        "Sahara",
        "Willys Sport",
        "Willys",
        "Latitude Plus",
        "Altitude",
        "Latitude",
        "Sport S",
        "Sport",
        "Laredo",
    ),
    "toyota": (
        "Capstone",
        "1794",
        "Platinum",
        "Limited",
        "XLE Premium",
        "TRD Pro",
        "XSE",
        "XLE",
        "TRD Off-Road",
        "TRD Sport",
        "TRD",
        "Adventure",
        "SE",
        "LE",
        "SR5",
        "SR",
        "Base",
    ),
    "honda": (
        "Type R",
        "Black Edition",
        "Sport Touring",
        "Elite",
        "Touring",
        "EX-L",
        "TrailSport",
        "Sport",
        "EX",
        "LX",
        "SE",
    ),
    "nissan": (
        "Platinum Reserve",
        "Platinum",
        "SL",
        "Nismo",
        "Pro-4X",
        "SV",
        "SR",
        "Rock Creek",
        "Pro-X",
        "Midnight Edition",
        "S",
    ),
    "hyundai": (
        "Calligraphy",
        "Limited",
        "N",
        "N Line",
        "SEL Premium",
        "SEL",
        "XRT",
        "SE",
        "Blue",
        "Essential",
        "Preferred",
    ),
    "kia": (
        "SX Prestige",
        "SX",
        "GT",
        "GT-Line",
        "EX",
        "X-Line",
        "S",
        "LX",
    ),
    "subaru": (
        "Touring XT",
        "Touring",
        "Wilderness",
        "Limited XT",
        "Limited",
        "Onyx Edition",
        "Sport",
        "Premium",
        "Base",
    ),
    "mazda": (
        "Turbo Premium Plus",
        "Turbo Premium",
        "Signature",
        "Premium Plus",
        "Premium",
        "Carbon Turbo",
        "Carbon Edition",
        "Preferred",
        "Select",
        "Sport",
    ),
    "volkswagen": (
        "R",
        "GTI",
        "GLI",
        "SEL Premium",
        "SEL",
        "R-Line",
        "SE",
        "S",
    ),
    "bmw": (
        "M Competition",
        "Competition",
        "M Sport",
        "Sport Line",
        "Luxury Line",
        "Modern Line",
        "xLine",
        "Executive",
        "Premium",
        "Base",
    ),
    "mercedesbenz": (
        "Maybach",
        "AMG",
        "AMG Line",
        "Premium Plus",
        "Premium",
        "Night Edition",
        "Exclusive",
        "Base",
    ),
    "audi": (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
        "Progressiv",
        "Technik",
        "Komfort",
    ),
    "lexus": (
        "Ultra Luxury",
        "Luxury",
        "F Sport Performance",
        "F Sport Handling",
        "F Sport",
        "Premium",
        "Base",
    ),
    "acura": (
        "Type S Advance",
        "Type S",
        "Advance",
        "Technology",
        "A-Spec",
        "Base",
    ),
    "cadillac": (
        "V-Series Blackwing",
        "V-Series",
        "Platinum",
        "Sport Platinum",
        "Premium Luxury",
        "Luxury",
        "Sport",
        "Preferred",
    ),
    "lincoln": (
        "Black Label",
        "Reserve",
        "Select",
        "Standard",
    ),
    "buick": (
        "Avenir",
        "Essence",
        "Sport Touring",
        "Preferred",
        "Select",
        "Base",
    ),
    "chrysler": (
        "Pinnacle",
        "Limited",
        "Touring L",
        "Touring Plus",
        "Touring",
    ),
    "dodge": (
        "SRT Hellcat Redeye Widebody",
        "SRT Hellcat Redeye",
        "SRT Hellcat",
        "Hellcat",
        "Scat Pack Widebody",
        "Scat Pack",
        "R/T Scat Pack",
        "Daytona Scat Pack",
        "Daytona R/T Scat Pack",
        "Daytona",
        "Citadel",
        "R/T Plus",
        "R/T",
        "GT",
        "Limited",
        "Premium",
        "SXT Plus",
        "SXT",
        "Pursuit",
        "Crew",
        "Sport",
        "SE Plus",
        "SE",
        "Express",
    ),
    "tesla": (
        "Plaid",
        "Performance",
        "Long Range",
        "Standard Range",
        "Base",
    ),
    "rivian": (
        "Ascend",
        "Adventure",
        "Explore",
    ),
    "porsche": (
        "GT3 RS",
        "GT3",
        "Turbo S",
        "Turbo",
        "GTS",
        "Carrera S",
        "S",
        "Carrera",
        "Base",
    ),
    "volvo": (
        "Ultra",
        "Ultimate",
        "Plus",
        "Core",
    ),
    "genesis": (
        "Sport Prestige",
        "Prestige",
        "Advanced",
        "Base",
    ),
    "landrover": (
        "Autobiography",
        "SV",
        "HSE",
        "HST",
        "SE",
        "Standard",
    ),
    "infiniti": (
        "Autograph",
        "Sensory",
        "Luxe",
        "Pure",
    ),
}

# Model-specific trim ladders (luxury-first). Used before make-wide lists.
MODEL_TRIM_ORDER: dict[tuple[str, str], tuple[str, ...]] = {
    ("bmw", "x2"): (
        "M35i",
        "xDrive28i",
        "sDrive28i",
    ),
    ("bmw", "i4"): (
        "M50 Gran Coupe",
        "M50",
        "M60 xDrive",
        "xDrive40",
        "eDrive40",
        "eDrive35",
    ),
    ("bmw", "x3"): (
        "M Competition",
        "M40i",
        "xDrive30e",
        "xDrive30i",
        "sDrive30i",
        "xDrive28i",
    ),
    ("bmw", "x5"): (
        "M Competition",
        "M60i xDrive",
        "M60i",
        "xDrive50i",
        "M50i",
        "xDrive45e",
        "xDrive40i",
        "sDrive40i",
    ),
    ("bmw", "x6"): (
        "M Competition",
        "M60i xDrive",
        "M60i",
        "xDrive40i",
    ),
    ("bmw", "i5"): (
        "M60 xDrive",
        "xDrive40",
        "eDrive40",
    ),
    ("bmw", "5series"): (
        "M550i",
        "550e",
        "540i",
        "530i",
        "530e",
    ),
    ("bmw", "3series"): (
        "M340i",
        "340i",
        "330e",
        "330i",
        "328i",
        "335i",
        "320i",
    ),
    ("bmw", "ix"): (
        "xDrive50",
        "xDrive40",
        "M60",
    ),
    ("bmw", "i7"): (
        "xDrive60",
        "eDrive50",
    ),
    ("jeep", "wagoneer"): (
        "L Series III",
        "L Series II",
        "L Series I",
        "Series III",
        "Series II",
        "Series I",
        "Carbide",
        "Obsidian",
        "Launch Edition",
    ),
    ("jeep", "grandcherokee"): (
        "Trackhawk",
        "SRT",
        "Summit Reserve",
        "Summit",
        "High Altitude",
        "Overland",
        "Trailhawk",
        "Limited X",
        "Limited",
        "Laredo",
    ),
    ("honda", "accord"): (
        "Touring Hybrid",
        "Sport-L Hybrid",
        "EX-L Hybrid",
        "Sport Hybrid",
        "SE",
        "LX",
    ),
    ("jeep", "renegade"): (
        "Trailhawk",
        "Limited",
        "Latitude",
        "Sport",
        "Altitude",
    ),
    ("chevrolet", "captivasport"): (
        "LTZ",
        "LT",
        "LS",
    ),
    ("volvo", "ex90"): (
        "Ultra",
        "Ultimate",
        "Plus",
        "Core",
    ),
    ("volvo", "ex30"): (
        "Ultra",
        "Plus",
        "Core",
    ),
    ("toyota", "bz"): (
        "Limited",
        "Woodland",
        "XLE",
        "AWD Limited",
        "AWD",
    ),
    ("toyota", "crownsignia"): (
        "Limited",
        "XLE",
    ),
    ("toyota", "grsupra"): (
        "3.0 Premium",
        "3.0",
        "2.0",
    ),
    ("toyota", "corolla"): (
        "XSE",
        "SE",
        "XLE",
        "LE",
        "Hybrid",
    ),
    ("chrysler", "pacifica"): (
        "Pinnacle",
        "Limited",
        "Touring L",
        "Touring Plus",
        "Touring",
        "Select",
        "Hybrid",
    ),
    ("mini", "cooper"): (
        "Iconic",
        "Signature Plus",
        "Classic",
        "Cooper S",
        "Cooper",
    ),
    ("bmw", "2series"): (
        "M240i",
        "M235",
        "230i",
        "228",
    ),
    ("bmw", "4series"): (
        "M440i",
        "430i",
        "428i",
    ),
    ("bmw", "8series"): (
        "M850i",
        "840i",
        "840",
    ),
    ("audi", "a8"): (
        "L",
        "60 TFSI",
        "55 TFSI",
        "Premium Plus",
        "Premium",
    ),
    ("audi", "r8"): (
        "V10 performance",
        "V10 Plus",
        "V10 RWD",
        "V10 quattro",
        "RWD",
        "AWD",
    ),
    ("audi", "r8spyder"): (
        "V10 performance",
        "V10 Plus",
        "V10 quattro",
        "RWD",
        "AWD",
    ),
    ("audi", "q6etron"): (
        "Premium Plus",
        "Premium",
        "Prestige",
        "Ultra",
        "quattro",
    ),
    ("audi", "q8etron"): (
        "Premium Plus",
        "Premium",
        "Prestige",
        "S line",
    ),
    ("audi", "rs6"): (
        "RS 6 Avant",
        "RS 6",
        "RS6",
    ),
    ("audi", "q5"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
        "Sport",
    ),
    ("audi", "a4"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
        "Sport",
    ),
    ("audi", "a6"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
    ),
    ("audi", "a3"): (
        "Premium Plus",
        "Premium",
        "S line",
    ),
    ("audi", "q7"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
    ),
    ("audi", "q8"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
    ),
    ("audi", "q8"): (
        "Prestige",
        "Premium Plus",
        "Premium",
        "S line",
    ),
    ("jeep", "compass"): (
        "Limited",
        "Trailhawk",
        "High Altitude",
        "Latitude Lux",
        "Latitude",
        "Altitude",
        "Sport",
    ),
    ("landrover", "rangerover"): (
        "Autobiography",
        "SV",
        "HSE",
        "HST",
        "SE",
    ),
    ("tesla", "model3"): (
        "Plaid",
        "Performance",
        "Long Range",
        "Standard Range",
    ),
    ("tesla", "modely"): (
        "Plaid",
        "Performance",
        "Long Range",
        "Standard Range",
    ),
    ("volvo", "xc90"): (
        "T8",
        "B6",
        "B5",
    ),
    ("gmc", "yukon"): (
        "Denali Ultimate",
        "Denali",
        "AT4",
        "SLT",
        "SLE",
        "Elevation",
    ),
    ("toyota", "tacoma"): (
        "TRD Pro",
        "TRD Off-Road",
        "TRD Sport",
        "Limited",
        "SR5",
        "SR",
    ),
    ("toyota", "landcruiser"): (
        "First Edition",
        "1958",
        "Land Cruiser",
    ),
    ("toyota", "rav4prime"): (
        "XSE",
        "SE",
    ),
    ("nissan", "pathfinder"): (
        "Platinum",
        "SL",
        "SV",
        "S",
    ),
    ("porsche", "taycan"): (
        "Turbo S",
        "Turbo",
        "GTS",
        "4S",
        "Base",
    ),
    ("bmw", "z4"): (
        "M40i",
        "sDrive30i",
    ),
    ("bmw", "m2"): (
        "CS",
        "Competition",
        "Base",
    ),
    ("kia", "k5"): (
        "GT",
        "GT-Line",
        "EX",
        "LXS",
        "LX",
    ),
    ("mazda", "mazda3"): (
        "Turbo Premium Plus",
        "Turbo",
        "Premium Plus",
        "Preferred",
        "Select",
    ),
    ("cadillac", "escalade"): (
        "V-Series",
        "Platinum",
        "Premium Luxury",
        "Luxury",
        "Sport",
    ),
    ("cadillac", "xt4"): (
        "Premium Luxury",
        "Sport",
        "Luxury",
    ),
    ("jeep", "grandwagoneer"): (
        "Summit Reserve",
        "Summit",
        "Obsidian",
        "Carbide",
        "Upland",
        "Series III",
        "Series II",
        "Series I",
    ),
}

_BMW_MOTOR_TRIM_RE = re.compile(
    r"^(?:[xs]Drive\d{2}[ie]|M\d{2,3}i|M60i(?:xDrive)?|AlpinaXB7|M Competition|M Sport)$",
    re.I,
)
_BMW_EV_TRIM_RE = re.compile(r"\b(M60\s*xDrive|xDrive\d{2}|eDrive\d{2})\b", re.I)
_JEEP_WAGONEER_SERIES_TRIM_RE = re.compile(
    r"^(?:L Series [IVX]+|Series [IVX]+|Carbide|Obsidian|Launch Edition)$",
    re.I,
)

# Universal fallback when make-specific extraction finds nothing.
GENERIC_TRIM_ORDER: tuple[str, ...] = (
    "Platinum",
    "Limited",
    "Premium",
    "Touring",
    "XLE",
    "SEL",
    "LT",
    "Sport",
    "EX",
    "SE",
    "LE",
    "S",
    "Base",
)
