"""Site-admin data quality hub: incomplete listings, dealership issue stats, and
the nightly invariants report (backend/scripts/data_quality_invariants.py, run by
deploy/nightly_data_quality_invariants.sh)."""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

from flask import flash, redirect, render_template, url_for

from backend.db.dealerships_db import list_recent_dealerships
from backend.db.inventory_db import get_dealership_issue_stats
from backend.dealer.admin.incomplete_listings_api import incomplete_listings_count
from backend.dealer.admin.routes import _session_profile, store_admin_bp
from backend.utils.roles import is_admin_role

_log = logging.getLogger(__name__)

# Matches deploy/nightly_data_quality_invariants.sh: REPORT_JSON="$REPORT_DIR/invariants_${RUN_DATE}.json"
_INVARIANTS_REPORT_DIR = Path(__file__).resolve().parents[3] / "workspace" / "data_quality"
_INVARIANTS_REPORT_NAME_RE = re.compile(r"^invariants_(\d{8})\.json$")

#: Statuses a check can carry once compared against its baseline. Kept in sync with
#: backend.scripts.data_quality_invariants._FAIL_STATUSES / compare() by hand -- this
#: module intentionally does not import the script (it is a CLI entry point, not a
#: library the web process should pull in), so the set is small and stable enough to
#: duplicate rather than couple the two.
_INVARIANT_FAIL_STATUSES = {"REGRESSION", "NEW_DEFECT_CLASS", "NO_BASELINE", "ERROR"}


def _require_site_admin():
    p = _session_profile()
    if not p or not is_admin_role(p.get("role")):
        return None
    return p


def _latest_invariants_report_path() -> Path | None:
    """The most recently DATED ``invariants_<YYYYMMDD>.json``, by filename date --
    not by mtime, so a report regenerated by hand for an old date never jumps ahead
    of a genuinely newer nightly run."""
    if not _INVARIANTS_REPORT_DIR.is_dir():
        return None
    dated = []
    for p in _INVARIANTS_REPORT_DIR.iterdir():
        m = _INVARIANTS_REPORT_NAME_RE.match(p.name)
        if m:
            dated.append((m.group(1), p))
    if not dated:
        return None
    dated.sort(key=lambda t: t[0])
    return dated[-1][1]


def _load_latest_invariants_report() -> dict[str, Any]:
    """
    The latest nightly invariants report, normalized for the template.

    Never raises: a missing, unreadable, or pre-item-6 (older) report must degrade
    the hub section to "no report" / "unknown" rather than 500 the whole page --
    this is a reporting surface layered onto a page that has other useful sections.
    """
    path = _latest_invariants_report_path()
    if path is None:
        return {"found": False, "path": None}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        _log.warning("could not read invariants report %s: %s", path, exc)
        return {"found": False, "path": str(path), "read_error": str(exc)}

    invariants = data.get("invariants") or []
    stored = [v for v in invariants if v.get("tier") == "stored"]
    rendered = [v for v in invariants if v.get("tier") == "rendered"]
    failing_ids = set(data.get("failing") or [])
    new_defect_ids = set(
        data.get("new_defect_classes")
        or [v["id"] for v in invariants if v.get("status") == "NEW_DEFECT_CLASS"]
    )

    return {
        "found": True,
        "path": str(path),
        "filename": path.name,
        "generated_at": data.get("generated_at"),
        "elapsed_sec": data.get("elapsed_sec"),
        "rendered_tier_ran": bool(data.get("rendered_tier_ran")),
        # Older reports (before the PARTIAL-coverage tag shipped) carry neither key;
        # absence must read as "full run", never as an unlabeled partial one.
        "sample_mode": bool(data.get("sample_mode", False)),
        "coverage": data.get("coverage", "full"),
        "stored": stored,
        "rendered": rendered,
        "failing_count": len(failing_ids),
        "new_defect_count": len(new_defect_ids),
        "new_defect_ids": sorted(new_defect_ids),
        "total_count": len(invariants),
        "overall_ok": len(failing_ids) == 0,
    }


@store_admin_bp.route("/data-quality")
def admin_data_quality_hub():
    if not _require_site_admin():
        flash("Data quality tools require a site admin account.", "error")
        return redirect(url_for("store_admin.admin_site_hub"))

    return render_template(
        "admin/data_quality.html",
        incomplete_count=incomplete_listings_count(),
        dealership_stats=get_dealership_issue_stats(limit=25),
        invariants_report=_load_latest_invariants_report(),
        invariant_fail_statuses=_INVARIANT_FAIL_STATUSES,
    )
